zeebe:
  client:
    cloud:
      clusterId: your cluster id
      clientId: your client id
      clientSecret: your client secret
    worker:
      defaultName: camunda-dmn-worker
      defaultType: DMN
      threads: 3

      dmn.repository: dmn-repo

    job.timeout: 10000

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.dmn: DEBUG

management:
  server:
    port: 8081

server.port: 8082
