zeebe:
  client:
    worker:
      defaultName: camunda-dmn-worker
      defaultType: DMN
      threads: 3

      dmn.repository: dmn-repo

    job.timeout: 10000
    broker.contactPoint: 127.0.0.1:26500
    security.plaintext: true

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.dmn: DEBUG

management:
  server:
    port: 8081
