zeebe:
  client:
#    cloud:
#      clusterId: <YOUR_CLUSTER_ID>
#      clientId: <YOUR_CLIENT_ID>
#      clientSecret: <YOUR_CLIENT_SECRET>
    worker:
      defaultName: camunda-dmn-worker
      defaultType: DMN
      threads: 3

      dmn.repository: dmn-repo

    job.timeout: 10000
    # remove the following two lines when using Camunda Cloud SaaS
    broker.gatewayAddress: 127.0.0.1:26500
    security.plaintext: true

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.dmn: DEBUG

management:
  server:
    port: 8081
