version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:1.2.4
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe-dmn-worker
    image: ghcr.io/camunda-community-hub/zeebe-dmn-worker:1.1.0
    environment:
      - zeebe.client.broker.gatewayAddress=zeebe:26500
      - zeebe.client.worker.dmn.repository=/usr/share/zeebe/dmn-repo
    volumes:
      - ./dmn-repo:/usr/share/zeebe/dmn-repo
    depends_on:
      - zeebe
    networks:
      - zeebe_network
