{{- with .Values.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" $ }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    {{ toYaml . | nindent 4 }}
  selector:
    {{- include "chart.selectorLabels" $ | nindent 4 }}
{{- end }}
